<?php

// Register Custom Post Type
function classes_post_type() {

	$labels = array(
		'name'                  => _x( 'Classes', 'Post Type General Name', 'school' ),
		'singular_name'         => _x( 'Classe', 'Post Type Singular Name', 'school' ),
		'menu_name'             => __( 'Classes', 'school' ),
		'name_admin_bar'        => __( 'Classes', 'school' ),
		'archives'              => __( 'Classes Archives', 'school' ),
		'attributes'            => __( 'Classes Attributes', 'school' ),
		'parent_item_colon'     => __( 'Parent Classe:', 'school' ),
		'all_items'             => __( 'All Classes', 'school' ),
		'add_new_item'          => __( 'Add New Classes', 'school' ),
		'add_new'               => __( 'Add New', 'school' ),
		'new_item'              => __( 'New Classes', 'school' ),
		'edit_item'             => __( 'Edit Classes', 'school' ),
		'update_item'           => __( 'Update Classes', 'school' ),
		'view_item'             => __( 'View Classes', 'school' ),
		'view_items'            => __( 'View Classes', 'school' ),
		'search_items'          => __( 'Search Classes', 'school' ),
		'not_found'             => __( 'Not found', 'school' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'school' ),
		'featured_image'        => __( 'Featured Image', 'school' ),
		'set_featured_image'    => __( 'Set featured image', 'school' ),
		'remove_featured_image' => __( 'Remove featured image', 'school' ),
		'use_featured_image'    => __( 'Use as featured image', 'school' ),
		'insert_into_item'      => __( 'Insert into Classes', 'school' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Classes', 'school' ),
		'items_list'            => __( 'Classes list', 'school' ),
		'items_list_navigation' => __( 'Classes list navigation', 'school' ),
		'filter_items_list'     => __( 'Filter Classes list', 'school' ),
	);
	$args = array(
		'label'                 => __( 'Classe', 'school' ),
		'description'           => __( 'Classes', 'school' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'page-attributes' ),
		'taxonomies'            => array( 'classescat', 'grade' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => false,
		'menu_position'         => 50,
		'show_in_admin_bar'     => false,
		'show_in_nav_menus'     => false,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
    register_post_type( 'classes', $args );

    $labels = array(
		'name'                  => _x( 'Groups', 'Post Type General Name', 'school' ),
		'singular_name'         => _x( 'Group', 'Post Type Singular Name', 'school' ),
		'menu_name'             => __( 'Groups', 'school' ),
		'name_admin_bar'        => __( 'Groups', 'school' ),
		'archives'              => __( 'Groups Archives', 'school' ),
		'attributes'            => __( 'Groups Attributes', 'school' ),
		'parent_item_colon'     => __( 'Parent Group:', 'school' ),
		'all_items'             => __( 'All Groups', 'school' ),
		'add_new_item'          => __( 'Add New Groups', 'school' ),
		'add_new'               => __( 'Add New', 'school' ),
		'new_item'              => __( 'New Groups', 'school' ),
		'edit_item'             => __( 'Edit Groups', 'school' ),
		'update_item'           => __( 'Update Groups', 'school' ),
		'view_item'             => __( 'View Groups', 'school' ),
		'view_items'            => __( 'View Groups', 'school' ),
		'search_items'          => __( 'Search Groups', 'school' ),
		'not_found'             => __( 'Not found', 'school' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'school' ),
		'featured_image'        => __( 'Featured Image', 'school' ),
		'set_featured_image'    => __( 'Set featured image', 'school' ),
		'remove_featured_image' => __( 'Remove featured image', 'school' ),
		'use_featured_image'    => __( 'Use as featured image', 'school' ),
		'insert_into_item'      => __( 'Insert into Groups', 'school' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Groups', 'school' ),
		'items_list'            => __( 'Groups list', 'school' ),
		'items_list_navigation' => __( 'Groups list navigation', 'school' ),
		'filter_items_list'     => __( 'Filter Groups list', 'school' ),
	);
	$args = array(
		'label'                 => __( 'Group', 'school' ),
		'description'           => __( 'Groups', 'school' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'page-attributes' ),
		'taxonomies'            => array( 'classescat', 'grade' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => false,
		'menu_position'         => 50,
		'show_in_admin_bar'     => false,
		'show_in_nav_menus'     => false,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'groups', $args );
	
	$labels = array(
		'name'                  => _x( 'Schedules', 'Post Type General Name', 'school' ),
		'singular_name'         => _x( 'Schedule', 'Post Type Singular Name', 'school' ),
		'menu_name'             => __( 'Schedules', 'school' ),
		'name_admin_bar'        => __( 'Schedules', 'school' ),
		'archives'              => __( 'Schedules Archives', 'school' ),
		'attributes'            => __( 'Schedules Attributes', 'school' ),
		'parent_item_colon'     => __( 'Parent Schedule:', 'school' ),
		'all_items'             => __( 'All Schedules', 'school' ),
		'add_new_item'          => __( 'Add New Schedules', 'school' ),
		'add_new'               => __( 'Add New', 'school' ),
		'new_item'              => __( 'New Schedules', 'school' ),
		'edit_item'             => __( 'Edit Schedules', 'school' ),
		'update_item'           => __( 'Update Schedules', 'school' ),
		'view_item'             => __( 'View Schedules', 'school' ),
		'view_items'            => __( 'View Schedules', 'school' ),
		'search_items'          => __( 'Search Schedules', 'school' ),
		'not_found'             => __( 'Not found', 'school' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'school' ),
		'featured_image'        => __( 'Featured Image', 'school' ),
		'set_featured_image'    => __( 'Set featured image', 'school' ),
		'remove_featured_image' => __( 'Remove featured image', 'school' ),
		'use_featured_image'    => __( 'Use as featured image', 'school' ),
		'insert_into_item'      => __( 'Insert into Schedules', 'school' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Schedules', 'school' ),
		'items_list'            => __( 'Schedules list', 'school' ),
		'items_list_navigation' => __( 'Schedules list navigation', 'school' ),
		'filter_items_list'     => __( 'Filter Schedules list', 'school' ),
	);
	$args = array(
		'label'                 => __( 'Schedule', 'school' ),
		'description'           => __( 'Schedules', 'school' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'page-attributes' ),
		'taxonomies'            => array( 'classescat', 'grade' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => false,
		'menu_position'         => 50,
		'show_in_admin_bar'     => false,
		'show_in_nav_menus'     => false,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
    register_post_type( 'schedules', $args );
    
    $labels = array(
        'name'				    => __( 'Grades' ),
        'singular_name'			=> __( 'Grade' ),
        'search_items'			=> __( 'Search Grades' ),
        'popular_items'			=> __( 'Popular Grades' ),
        'all_items'			    => __( 'All Grades' ),
        'parent_item'			=> __( 'Parent Grade' ),
        'parent_item_colon'		=> __( 'Parent Grade'  ),
        'edit_item'			    => __( 'Edit Grade' ),
        'update_item'			=> __( 'Update Grade'),
        'add_new_item'			=> __( 'Add New Grade'),
        'new_item_name'			=> __( 'New Grade'),
        'add_or_remove_items'	=> __( 'Add or remove Grades'),
        'choose_from_most_used'	=> __( 'Choose from most used Grades'),
        'menu_name'			    => __( 'Grades'),
    );
    register_taxonomy(
        'grade',
        array('classes', 'groups', 'schedules'),
        array(
            'labels'            => $labels,
            'public'            => true,
            'show_in_nav_menus'	=> true,
            'hierarchical'		=> true,
            'query_var'		    => true,
            'rewrite'		    => true,
            'show_admin_column' => true ,
            'exclude_from_search'  => false,
        )
    );

    $labels = array(
        'name'				    => __( 'Categorys' ),
        'singular_name'			=> __( 'Category' ),
        'search_items'			=> __( 'Search Categorys' ),
        'popular_items'			=> __( 'Popular Categorys' ),
        'all_items'			    => __( 'All Categorys' ),
        'parent_item'			=> __( 'Parent Category' ),
        'parent_item_colon'		=> __( 'Parent Category'  ),
        'edit_item'			    => __( 'Edit Category' ),
        'update_item'			=> __( 'Update Category'),
        'add_new_item'			=> __( 'Add New Category'),
        'new_item_name'			=> __( 'New Category'),
        'add_or_remove_items'	=> __( 'Add or remove Categorys'),
        'choose_from_most_used'	=> __( 'Choose from most used Categorys'),
        'menu_name'			    => __( 'Categorys'),
    );
    register_taxonomy(
        'classescat',
        'classes',
        array(
            'labels'            => $labels,
            'public'            => true,
            'show_in_nav_menus'	=> true,
            'hierarchical'		=> true,
            'query_var'		    => true,
            'rewrite'		    => true,
            'show_admin_column' => true ,
            'exclude_from_search'  => false,
        )
    );

}
add_action( 'init', 'classes_post_type', 0 );

?>